### ISSUE TITLE
Practica 8: Tablas de verdad y crocodrile

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-pavos2#1]
[Practica2_Matematicas_Discretas_P3.pdf](https://github.com/user-attachments/files/17487860/Practica2_Matematicas_Discretas_P3.pdf)

**Comment by Berenice1719** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by A-Lorely-Z** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:23/25
Resultados y conclusiones:25/25
Total:98/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
